# -*- coding: utf-8 -*-
"""
Structured knowledge base extracted from AeroTech_ATX200_Maintenance_Manual.pdf
Every record below is traceable to a specific chapter/section/table in the source PDF.
This is the ONLY data source for the retriever -- no flight/telemetry data included.
"""

# ---------------------------------------------------------------------------
# 1. PARAMETERS  (Chapter 3, Table 3.1)
# one row per monitored parameter: normal / warning / critical bands + action
# ---------------------------------------------------------------------------
PARAMETERS = [
    dict(parameter_id="engine_temperature", display_name="Engine Temperature", unit="°C",
         normal_min=640, normal_max=676, warning_min=676, warning_max=696,
         critical_min=696, critical_max=None, critical_direction="above",
         recommended_action="Inspect cooling air ducts and combustion liner",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="exhaust_gas_temperature", display_name="Exhaust Gas Temperature (EGT)", unit="°C",
         normal_min=615, normal_max=648, warning_min=648, warning_max=668,
         critical_min=668, critical_max=None, critical_direction="above",
         recommended_action="Inspect turbine section; review fuel scheduling",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="oil_temperature", display_name="Oil Temperature", unit="°C",
         normal_min=82, normal_max=92, warning_min=92, warning_max=95,
         critical_min=95, critical_max=None, critical_direction="above",
         recommended_action="Inspect oil cooler and scavenge lines",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="oil_pressure", display_name="Oil Pressure", unit="PSI",
         normal_min=55, normal_max=61, warning_min=52, warning_max=55,
         critical_min=None, critical_max=52, critical_direction="below",
         recommended_action="Inspect oil pump, filter, and seals",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="fuel_flow", display_name="Fuel Flow", unit="kg/hr",
         normal_min=2235, normal_max=2338, warning_min=2338, warning_max=2382,
         critical_min=2382, critical_max=None, critical_direction="above",
         recommended_action="Check fuel metering unit calibration",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="compressor_pressure", display_name="Compressor Pressure", unit="PSI",
         normal_min=38.5, normal_max=41.5, warning_min=41.5, warning_max=42.7,
         critical_min=42.7, critical_max=None, critical_direction="above",
         recommended_action="Inspect variable stator vane schedule",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="engine_vibration", display_name="Engine Vibration", unit="mm/s",
         normal_min=0, normal_max=3.1, warning_min=3.1, warning_max=4.7,
         critical_min=4.7, critical_max=None, critical_direction="above",
         recommended_action="Inspect bearing assembly and rotating components",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="hydraulic_pressure", display_name="Hydraulic Pressure", unit="PSI",
         normal_min=2950, normal_max=3050, warning_min=None, warning_max=None,
         critical_min=None, critical_max=None, critical_direction="outside_band",
         recommended_action="Stable parameter; verify against reservoir level only",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="engine_rpm", display_name="Engine RPM (N1)", unit="RPM",
         normal_min=9700, normal_max=9900, warning_min=None, warning_max=None,
         critical_min=None, critical_max=None, critical_direction="outside_band",
         recommended_action="Stable parameter; cross-check governor calibration",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="ambient_humidity", display_name="Ambient Humidity", unit="%RH",
         normal_min=20, normal_max=88, warning_min=88, warning_max=95,
         critical_min=95, critical_max=None, critical_direction="above",
         recommended_action="Monitor for ice/water ingestion risk",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="ambient_temperature", display_name="Ambient Temperature", unit="°C",
         normal_min=-10, normal_max=35, warning_min=35, warning_max=40,
         critical_min=40, critical_max=None, critical_direction="above",
         recommended_action="Apply hot-weather start procedure",
         source="Ch.3 Table 3.1"),
    dict(parameter_id="outside_air_temperature", display_name="Outside Air Temperature (OAT)", unit="°C",
         normal_min=-19, normal_max=28, warning_min=28, warning_max=37,
         critical_min=37, critical_max=None, critical_direction="above",
         recommended_action="Review derate tables before takeoff",
         source="Ch.3 Table 3.1"),
]

# aliases so query-time parameter names (however phrased) map to a parameter_id
PARAMETER_ALIASES = {
    "engine_temperature": ["engine temp", "engine temperature", "core temperature", "case temperature"],
    "exhaust_gas_temperature": ["egt", "exhaust gas temp", "exhaust gas temperature", "turbine exit temp"],
    "oil_temperature": ["oil temp", "oil temperature"],
    "oil_pressure": ["oil pressure", "oil psi", "lube pressure"],
    "fuel_flow": ["fuel flow", "fuel flow rate"],
    "compressor_pressure": ["compressor pressure", "compressor discharge pressure", "cdp"],
    "engine_vibration": ["vibration", "engine vibration", "vib"],
    "hydraulic_pressure": ["hydraulic pressure", "hyd pressure"],
    "engine_rpm": ["rpm", "n1", "engine speed", "engine rpm"],
    "ambient_humidity": ["humidity", "ambient humidity", "%rh"],
    "ambient_temperature": ["ambient temp", "ambient temperature"],
    "outside_air_temperature": ["oat", "outside air temp", "outside air temperature"],
}

# ---------------------------------------------------------------------------
# 2. SENSORS  (Chapter 4, sections 4.1-4.10)
# ---------------------------------------------------------------------------
SENSORS = [
    dict(sensor_id="4.1", parameter_id="engine_temperature", name="Engine Temperature Sensor",
         purpose="Monitors core engine case temperature as a primary thermal health indicator",
         location="Compressor case, mid-span thermocouple",
         inspection_method="Signal trend review each flight cycle; calibration check at 250-hour interval",
         expected_behaviour="Stable within 640-676°C across normal power range, rising predictably with thrust setting",
         failure_symptoms="Sustained reading above 676°C, erratic fluctuation, or drift from EGT-correlated trend",
         source="Ch.4.1"),
    dict(sensor_id="4.2", parameter_id="engine_vibration", name="Vibration Sensor (Accelerometer)",
         purpose="Detects rotor imbalance, bearing wear, and rotating assembly degradation",
         location="Mounted on forward and aft engine casing",
         inspection_method="Visual mount check; signal trend review each flight cycle",
         expected_behaviour="Stable within 0-3.1 mm/s under normal conditions; gradual upward trend signals developing wear",
         failure_symptoms="Sustained reading above 3.1 mm/s, erratic spikes, or signal dropout",
         source="Ch.4.2"),
    dict(sensor_id="4.3", parameter_id="exhaust_gas_temperature", name="Exhaust Gas Temperature (EGT) Probe",
         purpose="Monitors turbine inlet/exit gas temperature as a primary indicator of hot-section health",
         location="Turbine exhaust duct, multiple probes averaged",
         inspection_method="Borescope check of probe tip during scheduled inspection",
         expected_behaviour="Stable within 615-648°C at steady throttle; rises predictably with EGT-to-temperature ratio maintained",
         failure_symptoms="Sustained reading above 648°C, probe open/short circuit, frozen reading, or abnormal spread between probes",
         source="Ch.4.3"),
    dict(sensor_id="4.4", parameter_id="oil_temperature", name="Oil Temperature Sensor",
         purpose="Monitors lubrication system thermal condition",
         location="Oil return line, downstream of bearing chambers",
         inspection_method="Calibration check at scheduled intervals",
         expected_behaviour="Stable within 82-92°C; tracks engine temperature with minor lag",
         failure_symptoms="Sustained reading above 92°C, particularly when paired with a falling oil pressure trend",
         source="Ch.4.4"),
    dict(sensor_id="4.5", parameter_id="oil_pressure", name="Oil Pressure Transducer",
         purpose="Monitors lubrication system pressure and bearing/gearbox feed adequacy",
         location="Main oil supply line, downstream of oil pump",
         inspection_method="Calibration check at scheduled intervals",
         expected_behaviour="Stable within 55-61 PSI, proportional to RPM",
         failure_symptoms="Sustained reading below 55 PSI, fluctuating signal, or zero reading",
         source="Ch.4.5"),
    dict(sensor_id="4.6", parameter_id="fuel_flow", name="Fuel Flow Transmitter",
         purpose="Measures fuel mass flow to the combustion chamber",
         location="Fuel supply line upstream of fuel manifold",
         inspection_method="Flow calibration check during scheduled inspection",
         expected_behaviour="Stable within 2235-2338 kg/hr at steady throttle; tracks throttle position with minimal lag",
         failure_symptoms="Sustained reading above 2338 kg/hr at constant throttle, or mismatch with throttle position",
         source="Ch.4.6"),
    dict(sensor_id="4.7", parameter_id="compressor_pressure", name="Compressor Discharge Pressure Sensor",
         purpose="Monitors HP compressor discharge pressure",
         location="HP compressor exit duct",
         inspection_method="Leak check of pressure tap during inspection",
         expected_behaviour="Stable within 38.5-41.5 PSI, rising smoothly with RPM",
         failure_symptoms="Sustained reading above 41.5 PSI, pressure plateau, or oscillation indicating stall risk",
         source="Ch.4.7"),
    dict(sensor_id="4.8", parameter_id="hydraulic_pressure", name="Hydraulic Pressure Transducer",
         purpose="Monitors engine-driven hydraulic pump output",
         location="Hydraulic pump discharge line",
         inspection_method="Reservoir level check and pressure verification at scheduled inspection",
         expected_behaviour="Stable within 2950-3050 PSI across all normal operating conditions",
         failure_symptoms="Reading outside the stable band, combined with visible fluid loss or reservoir depletion",
         source="Ch.4.8"),
    dict(sensor_id="4.9", parameter_id="engine_rpm", name="Engine Speed Sensor (N1 Tachometer)",
         purpose="Monitors low-pressure spool rotational speed",
         location="LP shaft, forward of fan hub",
         inspection_method="Calibration check against governor reference at scheduled inspection",
         expected_behaviour="Stable within 9700-9900 RPM at commanded power settings",
         failure_symptoms="Reading outside the stable band without corresponding throttle command, or erratic governor response",
         source="Ch.4.9"),
    dict(sensor_id="4.10a", parameter_id="ambient_humidity", name="Ambient Condition Sensors (Humidity)",
         purpose="Provide environmental context for engine performance correction and icing risk assessment",
         location="Aircraft skin probes and pitot-static system",
         inspection_method="Cross-check against ground station reference during pre-flight inspection",
         expected_behaviour="Tracks local environmental conditions; used to contextualize engine parameter trends rather than as a standalone health indicator",
         failure_symptoms="Reading inconsistent with ground reference, or humidity above 88% combined with OAT near freezing, indicating icing risk",
         source="Ch.4.10"),
    dict(sensor_id="4.10b", parameter_id="ambient_temperature", name="Ambient Condition Sensors (Ambient Temp)",
         purpose="Provide environmental context for engine performance correction and icing risk assessment",
         location="Aircraft skin probes and pitot-static system",
         inspection_method="Cross-check against ground station reference during pre-flight inspection",
         expected_behaviour="Tracks local environmental conditions; used to contextualize engine parameter trends rather than as a standalone health indicator",
         failure_symptoms="Reading inconsistent with ground reference",
         source="Ch.4.10"),
    dict(sensor_id="4.10c", parameter_id="outside_air_temperature", name="Ambient Condition Sensors (OAT)",
         purpose="Provide environmental context for engine performance correction and icing risk assessment",
         location="Aircraft skin probes and pitot-static system",
         inspection_method="Cross-check against ground station reference during pre-flight inspection",
         expected_behaviour="Tracks local environmental conditions; used to contextualize engine parameter trends rather than as a standalone health indicator",
         failure_symptoms="Reading inconsistent with ground reference, or humidity above 88% combined with OAT near freezing, indicating icing risk",
         source="Ch.4.10"),
]

# ---------------------------------------------------------------------------
# 3. FAILURE MODES  (Chapter 5, sections 5.1.1-5.2.6)
#    parameters = list of parameter_ids this failure mode's detection logic references
# ---------------------------------------------------------------------------
FAILURE_MODES = [
    dict(failure_mode_id="5.1.1", name="Bearing Wear", section_type="primary",
         parameters=["engine_vibration", "engine_temperature", "exhaust_gas_temperature"],
         symptoms="Rising vibration trend, audible roughness at idle, gradual engine and EGT temperature creep",
         possible_causes="Lubrication breakdown, contamination, fatigue of rolling elements",
         detection_logic="Vibration sustained above 3.1 mm/s, frequently accompanied by engine temperature above 696°C and EGT above 668°C",
         severity="Medium to High",
         immediate_action="Schedule borescope and oil debris check within 20 flight cycles",
         engineering_recommendation="Inspect and replace bearing per Chapter 6.5 if vibration remains in the Critical band after re-check",
         source="Ch.5.1.1"),
    dict(failure_mode_id="5.1.2", name="Sensor Fault", section_type="primary",
         parameters=[],  # cross-parameter, not tied to one specific parameter
         symptoms="Erratic, frozen, or inconsistent reading on one or more channels without a corresponding physical trend",
         possible_causes="Wiring fault, connector corrosion, sensor element drift or failure",
         detection_logic="Reading inconsistent with cross-referenced parameters; vibration and temperature readings elevated but below Critical thresholds with no consistent physical pattern",
         severity="Low to Medium",
         immediate_action="Cross-check with redundant sensor or ground test set where available",
         engineering_recommendation="Calibrate or replace the affected sensor per Chapter 9 work order procedure",
         source="Ch.5.1.2"),
    dict(failure_mode_id="5.1.3", name="Hydraulic Leak", section_type="primary",
         parameters=["hydraulic_pressure", "engine_vibration", "oil_pressure"],
         symptoms="Hydraulic pressure outside the stable 2950-3050 PSI band, visible fluid loss, elevated vibration",
         possible_causes="Seal wear, fitting failure, pump wear",
         detection_logic="Hydraulic pressure deviation combined with vibration above 4.7 mm/s and oil pressure trending below 55 PSI",
         severity="Medium to High",
         immediate_action="Inspect reservoir level and visible lines before further flight",
         engineering_recommendation="Replace affected seal or fitting; verify pump output meets reference band",
         source="Ch.5.1.3"),
    dict(failure_mode_id="5.1.4", name="Oil Leakage", section_type="primary",
         parameters=["oil_pressure", "engine_vibration"],
         symptoms="Oil pressure decline, visible staining, low oil quantity, elevated vibration",
         possible_causes="Seal degradation, loose fitting, cracked supply or return line",
         detection_logic="Oil pressure below 52 PSI combined with vibration above 4.7 mm/s",
         severity="High",
         immediate_action="Ground aircraft; perform visual leak check before further flight",
         engineering_recommendation="Replace seal or line; verify root cause and oil quantity before return to service",
         source="Ch.5.1.4"),
    dict(failure_mode_id="5.2.1", name="Fuel Leakage", section_type="additional",
         parameters=["fuel_flow"],
         symptoms="Fuel odor, visible wetting, unexplained flow discrepancy",
         possible_causes="Fitting failure, line chafing, seal wear",
         detection_logic="Cross-check fuel flow transmitter against fuel quantity indication",
         severity="High",
         immediate_action="Ground aircraft immediately; isolate fuel supply",
         engineering_recommendation="Inspect and replace affected fuel line or fitting",
         source="Ch.5.2.1"),
    dict(failure_mode_id="5.2.2", name="Compressor Stall", section_type="additional",
         parameters=["compressor_pressure", "exhaust_gas_temperature", "engine_rpm"],
         symptoms="Bang/surge noise, RPM fluctuation, EGT spike",
         possible_causes="Foreign object damage, variable vane schedule fault, icing",
         detection_logic="Compressor discharge pressure above 42.7 PSI combined with EGT spike",
         severity="High",
         immediate_action="Reduce power; inspect for foreign object damage",
         engineering_recommendation="Inspect variable stator vane actuation; borescope compressor",
         source="Ch.5.2.2"),
    dict(failure_mode_id="5.2.3", name="Turbine Blade Damage", section_type="additional",
         parameters=["exhaust_gas_temperature", "engine_vibration"],
         symptoms="Localized EGT spike, vibration increase",
         possible_causes="Foreign object ingestion, thermal fatigue, erosion",
         detection_logic="Borescope inspection findings combined with EGT asymmetry above 668°C",
         severity="High",
         immediate_action="Ground aircraft; full borescope inspection",
         engineering_recommendation="Blade replacement or repair per engineering disposition",
         source="Ch.5.2.3"),
    dict(failure_mode_id="5.2.4", name="Combustion Instability", section_type="additional",
         parameters=["exhaust_gas_temperature", "fuel_flow"],
         symptoms="Audible rumble, EGT fluctuation at steady throttle",
         possible_causes="Fuel nozzle fouling, uneven fuel distribution",
         detection_logic="EGT spread across probes exceeds expected tolerance at constant fuel flow",
         severity="Medium",
         immediate_action="Inspect fuel nozzles for fouling/damage",
         engineering_recommendation="Clean or replace fuel nozzles; verify fuel pressure",
         source="Ch.5.2.4"),
    dict(failure_mode_id="5.2.5", name="High Exhaust Gas Temperature", section_type="additional",
         parameters=["exhaust_gas_temperature"],
         symptoms="EGT consistently elevated for a given power setting",
         possible_causes="Turbine wear, cooling air blockage, fuel scheduling fault",
         detection_logic="EGT trend exceeds 668°C at constant throttle position",
         severity="Medium to High",
         immediate_action="Reduce thrust; schedule inspection",
         engineering_recommendation="Inspect turbine cooling passages and fuel control unit",
         source="Ch.5.2.5"),
    dict(failure_mode_id="5.2.6", name="Low Oil Pressure (Isolated)", section_type="additional",
         parameters=["oil_pressure"],
         symptoms="Oil pressure below normal range without accompanying vibration increase",
         possible_causes="Pump wear, blocked filter, low oil quantity",
         detection_logic="Oil pressure transducer reading below 55 PSI in isolation",
         severity="Medium to High",
         immediate_action="Check oil quantity and filter before further flight",
         engineering_recommendation="Replace oil pump or filter as indicated by inspection",
         source="Ch.5.2.6"),
]

# ---------------------------------------------------------------------------
# 4. PROCEDURES  (Chapter 6)
# ---------------------------------------------------------------------------
PROCEDURES = [
    dict(procedure_id="6.2", title="Oil System Inspection Procedure",
         parameters=["oil_pressure", "oil_temperature"],
         steps=[
             "Confirm engine has cooled to ambient-safe handling temperature.",
             "Check oil quantity against minimum dispatch level.",
             "Inspect oil filter for debris; record any metallic content found.",
             "Verify oil pressure transducer reading against ground-test reference.",
             "Record results on Inspection Report (see Chapter 9).",
         ],
         caution="Allow adequate cooling time before opening oil system access panels to avoid burn hazard.",
         source="Ch.6.2"),
    dict(procedure_id="6.3", title="Hydraulic System Inspection Procedure",
         parameters=["hydraulic_pressure"],
         steps=[
             "Inspect reservoir fluid level against minimum mark.",
             "Check visible hydraulic lines for seepage or chafing.",
             "Verify pump discharge pressure against reference table in Chapter 3.",
         ],
         caution=None,
         source="Ch.6.3"),
    dict(procedure_id="6.4", title="Compressor Inspection Procedure",
         parameters=["compressor_pressure"],
         steps=[
             "Perform visual inspection of fan and LP compressor blades for nicks or erosion.",
             "Borescope HP compressor stages per scheduled interval.",
             "Cross-check compressor discharge pressure sensor against Chapter 3 reference ranges.",
         ],
         caution=None,
         source="Ch.6.4"),
    dict(procedure_id="6.5", title="Bearing Inspection Procedure",
         parameters=["engine_vibration"],
         steps=[
             "Review vibration sensor trend data for the preceding 10 flight cycles.",
             "Perform oil debris analysis for metallic contamination.",
             "Borescope accessible bearing housings where vibration trend exceeds 3.1 mm/s.",
             "Replace bearing where vibration trend exceeds 4.7 mm/s or oil debris confirms wear.",
             "Disposition per Maintenance Decision Matrix (Chapter 8).",
         ],
         caution=None,
         source="Ch.6.5"),
]

INSPECTION_INTERVALS = [
    dict(name="Post-Flight Walkaround", trigger="Every landing",
         key_checks="Visual leak check, fluid stains, foreign object damage", source="Ch.6.1 Table 6.1"),
    dict(name="50-Cycle Inspection", trigger="Every 50 flight cycles",
         key_checks="Oil quantity, vibration trend review, visual fan blade check", source="Ch.6.1 Table 6.1"),
    dict(name="100-Cycle Inspection", trigger="Every 100 flight cycles",
         key_checks="Borescope of hot section, fuel nozzle visual check", source="Ch.6.1 Table 6.1"),
    dict(name="250-Hour Inspection", trigger="Every 250 flight hours",
         key_checks="Full sensor calibration check, hydraulic system check", source="Ch.6.1 Table 6.1"),
    dict(name="Post-Vibration-Event Inspection", trigger="After abnormal vibration alert",
         key_checks="Bearing inspection, oil debris analysis", source="Ch.6.1 Table 6.1"),
    dict(name="Post-Exceedance Inspection", trigger="After temperature/pressure exceedance",
         key_checks="Borescope of affected section, engineering review", source="Ch.6.1 Table 6.1"),
]

# ---------------------------------------------------------------------------
# 5. TROUBLESHOOTING TREES  (Chapter 7)
# ---------------------------------------------------------------------------
TROUBLESHOOTING_TREES = [
    dict(tree_id="7.1", title="High Vibration Event", parameter_id="engine_vibration",
         steps=[
             "Step 1: Vibration reading exceeds Warning threshold (3.1 mm/s)",
             "Step 2: Check oil pressure and oil debris content",
             "Step 3a: If oil pressure normal (above 55 PSI) and no debris - continue monitoring, re-check next cycle",
             "Step 3b: If oil pressure below 55 PSI or debris present - proceed to bearing inspection",
             "Step 4: If bearing inspection confirms wear - replace bearing per Chapter 6.5",
             "Step 5: If vibration exceeds Critical threshold (4.7 mm/s) at any point - schedule inspection within 20 flight cycles per Chapter 8",
         ],
         source="Ch.7.1"),
    dict(tree_id="7.2", title="Low Oil Pressure Event", parameter_id="oil_pressure",
         steps=[
             "Step 1: Oil pressure reading falls below Warning threshold (55 PSI)",
             "Step 2: Check oil quantity against minimum dispatch level",
             "Step 3a: If oil quantity is low - replenish and monitor; investigate consumption rate",
             "Step 3b: If oil quantity is normal - inspect oil filter and pump",
             "Step 4: If pressure falls below Critical threshold (52 PSI) combined with elevated vibration - assess for oil leakage or hydraulic leak per Chapter 5.1",
         ],
         source="Ch.7.2"),
    dict(tree_id="7.3", title="High Exhaust Gas Temperature Event", parameter_id="exhaust_gas_temperature",
         steps=[
             "Step 1: EGT reading exceeds Warning threshold (648°C) at steady throttle",
             "Step 2: Cross-check EGT spread across all probes and corresponding engine temperature reading",
             "Step 3a: If spread is within tolerance and engine temperature is below 696°C - likely gradual turbine wear; schedule borescope",
             "Step 3b: If spread exceeds tolerance - suspect fuel nozzle fouling or localized hot spot",
             "Step 4: If EGT exceeds Critical threshold (668°C) - reduce power and inspect prior to further flight",
         ],
         source="Ch.7.3"),
]

# ---------------------------------------------------------------------------
# 6. DECISION MATRIX  (Chapter 8, Table 8.1)
# ---------------------------------------------------------------------------
DECISION_MATRIX = [
    dict(risk_min=0, risk_max=35, status="Healthy",
         typical_indicators="All parameters within Normal band; vibration below 3.1 mm/s",
         recommended_action="No action required; continue scheduled monitoring", source="Ch.8 Table 8.1"),
    dict(risk_min=35, risk_max=60, status="Monitor",
         typical_indicators="One or more parameters in Warning band; vibration 3.1-4.7 mm/s",
         recommended_action="Increase monitoring frequency; schedule inspection within defined interval", source="Ch.8 Table 8.1"),
    dict(risk_min=60, risk_max=100, status="Maintenance Due",
         typical_indicators="One or more parameters in Critical band; vibration above 4.7 mm/s",
         recommended_action="Inspect or replace affected component within 20 flight cycles", source="Ch.8 Table 8.1"),
]

GLOSSARY = {
    "EGT": "Exhaust Gas Temperature - temperature of gases exiting the turbine section",
    "N1": "Rotational speed of the low-pressure spool, expressed as a percentage",
    "Bleed Air": "Compressed air extracted from the compressor for cooling or pneumatic use",
    "Borescope": "Optical inspection tool used to examine internal engine components",
    "Disposition": "Engineering decision on repair, replace, or continue-monitoring status",
}
